config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

  resources :users do
      resources :user_books
  end
  resources :books
  resources :reviews
  resources :comments

  get '/home' => 'static_pages#home'
  get 'login', to: redirect('/auth/google_oauth2'), as: 'login'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  get '/signin' => 'sessions#new'
  post '/SignIn' => 'sessions#create'
  delete '/signout' => 'sessions#destroy'

  post '/createUserBook' => 'user_books#create'

end

app/models/user_book.rb
# == Schema Information
#
# Table name: user_books
#
#  id           :bigint(8)        not null, primary key
#  book_id      :integer
#  user_id      :integer
#  notes        :string(255)
#  started_date :datetime
#  read_date    :datetime
#  rating       :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class UserBook < ApplicationRecord
  belongs_to :user
  belongs_to :book

  after_create :add_user_activity;
  after_update :update_user_activity;


  private
  def add_user_activity
    activity = Activity.create(user_id:self.user_id,activity:"Created user book",book_id:self.book_id);
    activity.save;
  end

  def update_user_activity
    activity = Activity.create(user_id:self.user_id,activity:"Updated user book",book_id:self.book_id);
    activity.save;
  end
end

app/controllers/user_book_controller.rb
class UserBookController < ApplicationController

  before_action :authenticate
  skip_before_action :verify_authenticity_token

  def index
    @user = User.find(params[:user_id]);
  end

  def show
  end

  def edit
    @user = User.find(params[:user_id]);
    if !@user.nil?
      @user_book = @user.user_books.where("book_id=?",params[:id]).first;
      if !@user_book.nil?
        @book = @user.books.find(@user_book.book_id)
        @book_shelve = @user.book_shelves.where("book_id = ?",@user_book.book.id)
      end
    end

  end

  def update
    @user = User.find(params[:user_id]);
    if !@user.nil?
      @book = @user.books.find(params[:id])
      @user_book = @user.user_books.where("book_id=?",params[:id]).first
      if edit_params
        if @user_book.update_attributes(edit_params)
          flash[:success] = "Updated successfully"
        end
      end
      if shelve_params
        puts shelve_params
        @book_shelve = BookShelve.create(user_id:@user.id,book_id:@book.id,shelve_id:shelve_params[:shelve_id])
        @book_shelve.save;
      end
    end
    render 'edit'
  end

  def create
    @user = User.find(session[:user_id])
    if !@user.nil?
      @user_book = @user.user_books.find_or_create_by(book_id:params[:book_id]);
      flash[:success] = "Added to My Book List"
      redirect_to edit_user_user_book_path(@user,@user_book.book_id)
    end
  end

  def destroy
    @user = User.find(session[:user_id])
    if !@user.nil?
        @user_book = @user.user_books.find_or_create_by(book_id:params[:id]);
        if !@user_book.nil?
          UserBook.destroy(@user_book.id);
          flash[:success] = "Removed book from MyBook List"
          render 'index'
        end
    end
  end

private
  def edit_params
    params.fetch(:user_book,{}).permit(:notes,:rating,:started_date,:read_date);
  end

  def shelve_params
    params.fetch(:shelve_record,{}).permit(:shelve_id);
  end
end

app/controllers/user_books_controller.rb
class UserBooksController < ApplicationController

  before_action :authenticate
  skip_before_action :verify_authenticity_token

  def index
    @user = User.find(params[:user_id]);
  end

  def show
  end

  def edit
    @user = User.find(params[:user_id])
    if !@user.nil?
      @user_book = @user.user_books.where("book_id=?",params[:id]).first
      if !@user_book.nil?
        @book = @user.books.find(@user_book.book_id)
        @book_shelve = @user.book_shelves.where("book_id = ?",@user_book.book.id)
      end
    end

  end

  def update
    @user = User.find(params[:user_id]);
    if !@user.nil?
      @book = @user.books.find(params[:id])
      @user_book = @user.user_books.where("book_id=?",params[:id]).first
      if edit_params
        if @user_book.update_attributes(edit_params)
          flash[:success] = "Updated successfully"
        end
      end
      if shelve_params
        puts shelve_params
        @book_shelve = BookShelve.create(user_id:@user.id,book_id:@book.id,shelve_id:shelve_params[:shelve_id])
        @book_shelve.save;
      end
    end
    render 'edit'
  end

  def create
    puts  UserSession.find.user
    @user =  current_user
    if !@user.nil?
      @user_book = @user.user_books.find_or_create_by(book_id:params[:book_id]);
      flash[:success] = "Added to My Book List"
      UserMailer.activity_mail(@user,@user_book.book).deliver_later(wait: 1.minute)
      redirect_to edit_user_user_book_path(@user,@user_book.book_id)
    end
  end

  def destroy
    @user = User.find(session[:user_id])
    if !@user.nil?
        @user_book = @user.user_books.find_or_create_by(book_id:params[:id]);
        if !@user_book.nil?
          UserBook.destroy(@user_book.id);
          flash[:success] = "Removed book from MyBook List"
          render 'index'
        end
    end
  end

private
  def edit_params
    params.fetch(:user_book,{}).permit(:notes,:rating,:started_date,:read_date);
  end

  def shelve_params
    params.fetch(:shelve_record,{}).permit(:shelve_id);
  end
end

app/helpers/user_book_helper.rb
module UserBookHelper
  def get_shelves_name(books)
    @array ='';
   books.shelves.map{|a|  @array +=  a.shelve_nam }
  end
end

app/views/user_books/edit.html.erb
<script>
$( document ).ready(function() {
toggle_active()
});
function toggle_active(){
  $('#sidePane >a').removeClass('active')
  $('#userBookPane').addClass("active")
}
</script>

<%= render 'shared/book_details_form'%>
<%= form_for @user_book ,url: user_user_book_path(@user.id,@book.id) ,method:'put' do |f| %>
  <div class="form-inline">
    <div class="form-group">
      <%= f.label :notes,class:"form-label margin-10" %>:
      <%= f.text_area :notes ,value:@user_book.notes ,class:"form-control width50 margin-10"%>
      <%= button_tag(type: "submit", class: "btn btn-default margin-10") do %>
         <i class="fa fa-sticky-note-o"></i>Add
      <% end %>
    </div>
  </div>
<% end %>
<br/>

<%= form_for @user_book,url: user_user_book_path(@user.id,@book.id) ,method:'put' do |f| %>
  <div class="form-inline">
    <div class="form-group">
    <%= f.label :started_date,'Started Date:  ' ,class:"form-label margin-10"%>
    <%= f.date_select :started_date ,value:@user_book.started_date,class:"form-control width50 margin-10"%>

    <%= f.label :read_date,'Read Date:  ' ,class:"form-label margin-10" %>
    <%= f.date_select :read_date,value:@user_book.read_date,class:"form-control width50 margin-10" %>

    <%= f.submit 'Update' ,class:'margin-10' %>
    </div>
  </div>
<% end %>
<br/>

<%= form_for @user_book,remote:true,url: user_user_book_path(@user.id,@book.id) ,method:'put' do |f| %>
  <div class="form-inline">
    <div class="form-group">
    <%= f.label :rating ,class:"form-label margin-10"%>
    <%= f.text_field :rating ,value:@user_book.rating,class:"form-control width50 margin-10"%>
      <%= button_tag(type: "submit", class: "btn btn-default margin-10") do %>
         <i class="fa fa-star-o"></i>Rate
    <% end %>
    </div>
  </div>
<% end %>
<br/>

<%= form_for :shelve_record,remote:true,url:user_user_book_path(@user.id,@book.id) ,method:'put' do |f| %>
<%= f.collection_select :shelve_id, Shelve.all,:id,:shelve_nam,prompt: true%>
<%= f.submit 'add' %>
<% end %>
<br/>
<br/>
<div>
<h6> Activity </h6>
<ul>
<% @book.activities.each do |b|%>
<li>
<%= b.activity %> <span class="timestamp"> <%=time_ago_in_words(b.created_at)%></span>
</li>
<% end %>
</ul>
</div>

<br/><hr/>
<br/>
<%= render ('shared/reviews_details') %>

app/views/user_books/index.html.erb
<script>
$( document ).ready(function() {
toggle_active()
});
function toggle_active(){
  $('#sidePane >a').removeClass('active')
  $('#userBookPane').addClass("active")
}

</script>
<h4> My Books </h4>

<div class="fnt0">
<table class="fnt14 table">
    <thead>
      <th>Title</th>
      <th>Author</th>
      <th>Started Date</th>
      <th>Read Date</th>
      <th>Rating</th>
      <th>Added Date</th>
      <th>Shelve </th>
      <th></th>
    </thead>
    <tbody>
      <div class="fnt0">
      <%= @user.books.each { |b| %>
        <tr>
        <% @user_book = b.user_books.where("book_id=?",b.id).first %>
        <td> <%=b.title%></td>
        <td> <%=b.author.author_name %> </td>
        <td> <%=@user_book.started_date %> </td>
        <td> <%=@user_book.read_date %> </td>
        <td> <%=@user_book.rating %> </td>
        <td> <%=@user_book.created_at %> </td>
        <td> <%=get_shelves_name(b) %></td>
        <td> <%=link_to "edit" , edit_user_user_book_path(@user_book.user_id,@user_book.book_id),reload:true %></td>
        <td> <%=link_to "remove" , user_user_book_path(@user_book.user_id,@user_book.book_id),method:'delete',reload:true %></td>
      </tr>
      <% } %>
    </div>
    </tbody>
</table>
</div>

app/views/user_books/show.html.erb
<script>
$( document ).ready(function() {
toggle_active()
});
function toggle_active(){
  $('#sidePane >a').removeClass('active')
  $('#userBookPane').addClass("active")
}
</script>